### ISSUE TITLE
add an admins manual

### ISSUE THREAD

**Issue by Scanialady** [tas2580/privacyprotection#15]
It could be good to add an admins manual how to use this extension - which function is for what and where to find. Must not be a book, but informative.

Ich halte es für eine gute Idee, ein Benutzerhandbuch für den Admin einzufügen, wo die Funktionen beschrieben werden, und wo sie zu finden sind.

**Comment by tas2580** [comment]
Kannst du gerne machen, aber noch ist es zu früh dafür da sich immer wieder was ändert. Wenn ich es z.B. schaffe die Language Variable für die DS zu überschreiben und sie so im ACP bearbeitbar zu machen brauche ich ein neues ACP Modul dazu und kann dann alle anderen Einstellungen dort hin verlegen.
Wenn man das also jetzt schreibt läuft man Gefahr das irgendwann nochmal zu machen.

**Comment by tas2580** [comment]
https://github.com/tas2580/privacyprotection/wiki
