### ISSUE TITLE
Aus Gruppe entfernen

### ISSUE THREAD

**Issue by Joyce-Luna** [tas2580/privacyprotection#20]
Wenn ein User es ablehnt, landet er in der Gästegruppe.
Normal müsste er dann aus der registrierten Gruppe heraus fliegen. Tut er aber nicht.
Da müsstest du auch mal schauen.

Überlegt ein User es sich doch das zu akzeptieren wird  der Gast Zugang wieder entfernt. Das funktioniert.

**Comment by Scanialady** [comment]
Nein, das seh ich anders. Die Gästegruppe muss in dem Falle mit NIE-Berechtigungen bestückt sein, damit sie zusätzlich vergeben werden kann. Dann braucht man nicht umzugruppieren, und der Benutzer kann die bisherigen Bereiche weiternutzen - halt nur ohne Speichererlaubnis.

**Comment by Joyce-Luna** [comment]
Sehe ich anders. Es gibt Bereiche wo Gäste keinen Zugriff haben, Wer ablehnt der soll auch nicht das Recht haben dort zu lesen. So lange er auch die Berechtigung als registrierter User hat, so kann er weiterhin alles lesen.

**Comment by tas2580** [comment]
Kann er nicht wenn er in einer Gruppe ist die für den Bereich das Rechte "nie" hat. Unabhängig davon ob er über eine andere Gruppe Zugang zu dem Bereich hat.

**Comment by tas2580** [comment]
Kann er nicht wenn er in einer Gruppe ist die für den Bereich das Rechte "nie" hat. Unabhängig davon ob er über eine andere Gruppe Zugang zu dem Bereich hat.
