### ISSUE TITLE
Suggest merger with david63's Privacy Policy

### ISSUE THREAD

**Issue by 01i** [tas2580/privacyprotection#26]
Has there been any thoughts regarding integrating or merging this plugin with the work being done by david63?

https://www.phpbb.com/community/viewtopic.php?f=456&t=2464776
https://github.com/david63/david63-privacypolicy

There is some useful functionality in both plugins that's not in the other, but both plugins create their own incompatible policy pages so don't really work together in a satisfactory way.

If these two plugins were merged it would make both stronger.

**Comment by 01i** [comment]
Didn't think of that, Still wanted to suggest the idea of you two working together. One extension that does everything the two of you have achieved between you would be simpler to eventually roll into core when USA follows with similar laws.

**Comment by 01i** [comment]
Linking to the david63 policy page works, but both extensions include a link in the bottom bar. You end up with something like this: 

Board index, Contact us, **Cookie/Privacy policy**, The team, **Privacy policy**, Members, Delete all board cookies, All times are UTC

**Comment by tas2580** [comment]
I have no problem to work together with @david63 but now it's a little late. We have both extensions and to merge it into one would be a lot of work. If some functions will roll into core someone needs to write it new because core code is different form extension code.

> Linking to the david63 policy page works, but both extensions include a link in the bottom bar.

I have opend https://github.com/tas2580/privacyprotection/issues/29 to solve this problem

**Comment by 01i** [comment]
I know nothing about how easy or hard it is to merge an extension into core, I've not written a phpbb plugin since v2 when it was all so different. I just mentioned that because there was talk from developers in one of the big GPDR threads about which elements 'could' be included in core.

My main concern was in making sure the two of you knew of each others efforts. It's pretty hard work reading through the GPDR threads and finding the useful posts among all the other noise. Hence why I ended up posted on each of your githubs.

At least if the two of you are aware of each others extensions (assuming you were not already), you can avoid too much duplication of work and expand in different directions with extensions that play nicely with each other. 

Maybe once GPDR is in place and things calm down a bit, there might be an opportunity to work towards a combination extension.

**Comment by Scanialady** [comment]
Seems david63 is ready or has no time to work on his extension. Nothing changed the last weeks. He has created good extensions, but he seems to lack the time for maintenance and updating. I do not think he wants to spend more time working together. There are many extensions that would be better in a collaborative effort. Still, it was a good idea.

**Comment by jan-2017** [comment]
Die Extension von david63 ist nur in einer Sache "besser".
Wünschen würde ich mir die Option"Admin option to list who has accepted" 
Gruss Jan

**Comment by david63** [comment]
I have not been ignoring this discussion - just been trying to get RC2 out for my Privacy Policy.

Not sure about trying to merge two extensions, especially when they are at the stage they are at
