### ISSUE TITLE
Logout Link für Ablehnung

### ISSUE THREAD

**Issue by Joyce-Luna** [tas2580/privacyprotection#30]
Wenn ich bei ablehnen ein Logout Link setze kommt nach dem ablehnen dieser Text 
"Du wurdest nicht abgemeldet, da die Anfrage nicht zu deiner Sitzung passte. Bitte wende dich an die Board-Administration, sofern das Problem regelmäßig auftritt."
Ein Link zu einem weiteren Text wenn man ablehnt funktioniert in dem Fall ja.

**Comment by jan-2017** [comment]
Ja , das wäre optimal.Ein Link einfügen zu können , wenn nach dem Login die Datenschutzverordnung abgelehnt wird.Gruss Jan

**Comment by tas2580** [comment]
Mit `ucp.php?mode=logout&sid={SID}` sollte es jetzt funktionieren.

**Comment by jan-2017** [comment]
Muss ich hier nun (alle) User_IDs einsetzen? Oder werden nach dem Anklicken auf dem Link betreffende User ausgeloggt? Mfg Jan

**Comment by tas2580** [comment]
`{SID}` wird einfach durch die Session-ID des aktuellen Users ersetzt. Wenn du den Link einfach so kopierst (Domain davor) sollte es für alle deine User funktionieren.

**Comment by jan-2017** [comment]
Klappt perfekt.Nach einfügen des Links wird durch klicken auf "Datenschutz ablehnen" der User sofort ausgeloggt!Danke für diese Umsetzung! Gruss Jan
