### ISSUE TITLE
Auflistung in der ACP wer und wann akzeptiert hat

### ISSUE THREAD

**Issue by jan-2017** [tas2580/privacyprotection#31]
An Anlehnung an die extension von phpbb.com wäre mir in dem großen Forum das hier lieb:

1.Admin option to list who has accepted
2.The date/time of the acceptance is logged in the database

Wäre das machbar,dies nachzupflegen?

Gruß Jan

Nachtrag:

Es wäre super wenn man aus der ACP heraus eine Auflistung hätte ohne MySQL / phpbbmyadmin zu öffnen , wer allle akzeptiert oder abgelehnt hat. In der ACP im jeweiligen Benutzerfeld sieht man es aber das ist bei großen Foren sehr aufwendig.

**Comment by tas2580** [comment]
Um das Modul zu aktivieren muss man entweder die Extension komplett deinstallieren oder das Modul von Hand hinzufügen.

**Comment by jan-2017** [comment]
Der alte Datensatz wurde komplett entfernt und der aktuelle (mit allen Änderung vom 06.05.2018) installiert. Es werden alle Benutzer in der "Benutzerliste" angezeigt. Klickt man nun auf "Datenschutzerklärung akzeptieren" (von einen Testuser erscheint dieser User nicht mehr in der "Benutzerliste" , der vorher noch aufgelistet wurde.Auch die Moderatoren und Admins verschwinden aus der Liste. Gruss Jan

**Comment by tas2580** [comment]
So soll es doch sein. In der Liste erscheinen nach dem aktualisieren alle Benutzer. Wenn ein Benutzer akzeptiert verschwindet er aus der Liste. Es werden also alle Benutzer aufgelistet die aktuell nicht akzeptiert haben.
Bots werden nie aufgelistet, Admins oder Moderatoren werden wie normale Benutzer behandelt.

**Comment by jan-2017** [comment]
Entschuldigung , das habe ich falsch verstanden. Ich dachte in der Spalte "Zuletzt Akzeptiert" erscheinen von den Usern "Datum & Uhrzeit" wenn die DSVGO akzeptiert wurde. Aber so macht es irgendwie auch Sinn. Wobei die Spalte nun keine Funktion hat ;-) Grus Jan

**Comment by tas2580** [comment]
In der Spalte erscheint auch wann sie zuletzt akzeptiert haben, nur falls sie noch nie akzeptiert haben ist die Spalte leer. Das sollte sich aber mit der Zeit legen da für alle neuen User dort auf jeden Fall ein Wert eingetragen ist. Interessant wird es wenn man irgendwann seine DS aktualisiert.
Man könnte das jetzt noch erweitern und einen Schalter einbauen um alle User anzuzeigen die akzeptiert haben.

**Comment by Scanialady** [comment]
das wäre zu einem eventuell mal erfragten Nachweis sehr hilfreich. Das muss man ja auch im Auge behalten: dass man auf Anfrage Nachweise erbringen muss.
