### ISSUE TITLE
Not removed from group also if I accept the policies

### ISSUE THREAD

**Issue by b-vetter** [tas2580/privacyprotection#32]
Also if I accept the privacy policy (as registered user, after click on "Privacy policy updated" as admin), I be still in the group for the user which haven't accepted the policies.

---------

Auch wenn ich die neuen Datenschutzbestimmungen akzeptiere (als bestehender Benutzer, nach dem ich "Datenschutzerklärung wurde aktualisiert" als Admin gewählt habe), bleibe ich in der Gruppe drin, in der die Benutzer sind, die die Datenschutzbestimmungen nicht zugestimmt haben.

**Comment by jan-2017** [comment]
Bleibt es auch weiter bestehen , wenn du den Button "Datenschutzerklärung akzeptieren" zweimal anklicken musst? Wenn ich bei mir die Gruppe "Gäste wähle" dann loggt sich User xy ein , wird verschoben , klickt "Akzeptieren" und wird wieder zurückverschoben - laut ACP Protokoll - Mfg Jan

**Comment by tas2580** [comment]
Hast du zwischendrin mal die Gruppe in die verschoben wird geändert?

**Comment by tas2580** [comment]
Schau mal ob es damit behoben ist, wenn nicht muss ich hier wieder auf machen.

**Comment by b-vetter** [comment]
Bei mir tritt das Problem weiterhin auf.
Sobald ich die Bedingungen akzeptiere, fliege ich aus der Gruppe raus (wie es auch korrekt ist), werde dann aber direkt wieder aufgenommen.
Scheinbar liegt auch hier das Problem bei PHP 7.1.
