### ISSUE TITLE
Warning window is still visible if I click accept

### ISSUE THREAD

**Issue by b-vetter** [tas2580/privacyprotection#33]
If I accept the policies is the warning-window still visible. It is visible until I reload the window.

---

Wenn ich die Datenschutzbestimmungen akzeptiere, verschwindet nicht direkt das "Warnfenster". Erst wenn ich die Seite dann noch einmal neu lade, verschwindet dieses.

**Comment by jan-2017** [comment]
Diese Problem habe ich mit der aktuellen Version 0.2.1 BETA auch.
Klicke ich auf "Datenschutzerklärung akzeptieren" muss ich zweimal das anklicken bis die das "Warnfenster" verschwindet und das Forum wieder freigegeben ist. Habe aber zuvor auch auf "Ablehnen" geklickt um das "Logout" zu testen (was mit http://www.meineseite.com/ucp.php?mode=logout) nicht klappt.Das verschieben der User wenn abgelehnt wird kalppt und auch das wieder entfernen des Mitglieds wenn er auf akzeptieren klickt.Gruss Jan

**Comment by tas2580** [comment]
Welche PHP Version?

**Comment by b-vetter** [comment]
Bei mir die 7.1.13

**Comment by jan-2017** [comment]
Bei mir ist es die PHP Version 7.0.29 falls es dir weiterhelfen sollte

**Comment by tas2580** [comment]
Dachte mir schon das es an PHP > 7 liegt. Ich schau mal wie ich das gefixt bekomme.

**Comment by jan-2017** [comment]
Kleines Update bei meiner PHP Version (7.0.29) mit 3.2.0. : Nach dem Update mit dem "Code" der Änderungen bis zum 06.05.2018 ist das obige Fehlerbild nicht mehr nachvollziehbar. Gruß Jan

**Comment by b-vetter** [comment]
Problem ist (genau wie #32) bei mir unter 7.1 weiterhin vorhanden.
