### ISSUE TITLE
privacyprotection/acp/privacyprotection_module.php

### ISSUE THREAD

**Issue by Joyce-Luna** [tas2580/privacyprotection#36]
https://github.com/tas2580/privacyprotection/blob/8009a3f159a7ba07864e0afb360563900f58f194/acp/privacyprotection_module.php#L150

'PLACEHOLDER'      => htmlspecialchars(sprintf($this->user->lang['PRIVACY_POLICY'], $this->config['sitename'], generate_board_url())),

Meldung von Kirk https://www.phpbb.de/community/viewtopic.php?p=1382838#p1382838

**Comment by tas2580** [comment]
Die Frage ist soll das im Placeholder überhaupt übersetzt werden? Im HTML steht ja nachher auch `%1$s`

**Comment by tas2580** [comment]
https://github.com/tas2580/privacyprotection/issues/40
