### ISSUE TITLE
Datenschuz Link hervorheben

### ISSUE THREAD

**Issue by Joyce-Luna** [tas2580/privacyprotection#38]
'NEED_ACCEPT_PRIVACY'				=> 'Unsere <a href="%s">Datenschutzerklärung</a> hat sich geändert. Du musst die neue Datenschutzerklärung akzeptieren, um das Forum weiterhin nutzen zu können.',

Hier würde ich ein Underline setzen.

	'NEED_ACCEPT_PRIVACY'				=> 'Unsere <a href="%s"style="text-decoration:underline;">Datenschutzerklärung</a> hat sich geändert. Du musst die neue Datenschutzerklärung akzeptieren, um das Forum weiterhin nutzen zu können.',

Ist nicht bei jedem Forum Style zu erkennen das dort ein Link ist.

**Comment by tas2580** [comment]
Ist dann nicht eher das Style scheiße? Ein Link sollte doch immer irgendwie hervorgehoben werden.

**Comment by Joyce-Luna** [comment]
Kommt auf die Farben an die man im Style verwendet und ob man Rules einfärbt.
Also ein underline würde nicht schaden.
Das kann natürlich jeder auch für sich so machen, nach bedarf oder dem ganzen eine andere Farbe geben wie auch immer.

**Comment by Scanialady** [comment]
Da stimmt dann wohl was mit den Farben des Styles nicht, wenn man Links nicht erkennen kann. Ich würde das beim Standard belassen, der es den Styles überlässt, wie mit Links umzugehen ist - der Kompatibilität halber.

**Comment by tas2580** [comment]
Ich bin allgemein kein Fan von inline CSS und finde man sollte den Code (HTML & CSS) in Sprachdateien so gering wie möglich halten. Falls der Link nicht als Link erkennbar ist ist das ein Bug im Style, Links innerhalb von Beiträgen sind dann ja auch nicht erkennbar.
Man könnte jetzt in der Extension alles mögliche stylen weil es sicher noch mehr Styles gibt die irgendwo ein Problem haben, aber das ist nicht Aufgabe der Extension.

Ich mach hier erst mal zu, falls jemand noch ein Argument dafür hat kann ich ja wieder auf machen.
