### ISSUE TITLE
PHP Warning after selecting a group

### ISSUE THREAD

**Issue by jan-2017** [tas2580/privacyprotection#39]
**Describe the bug**
PHP Warning after selecting a group to move the user in

**To Reproduce**
1. Go to ACP / Extension / Privacy Protection / Settings
2. Choose a group
3. Click on Submit / Save
4. See error on the top 

**Expected behavior**
It appears an error in ACP window above:

`[phpBB Debug] PHP Warning: in file [ROOT]/ext/tas2580/privacyprotection/acp/privacyprotection_module.php on line 124: Invalid argument supplied for foreach()`

**Screenshots**
Only this text above

**Webserver (please complete the following information):**
 - phpBB Version: [3.2.0.]
 - PHP Version: [7.0.29]

**Additional context**
If i chosse in the drag & Drop list the entry to "Not Move" the error disappear.

**Comment by tas2580** [comment]
https://github.com/tas2580/privacyprotection/commit/75499dc8718a8c3643f95ed9df41c5d82f725a3c
