### ISSUE TITLE
Fix shortcodes for site name and URL in custom policies.

### ISSUE THREAD

**Issue by 01i** [tas2580/privacyprotection#40]
When modifying the default policy, the language file shortcodes %1%s and %2$s do not work. I suspect that's because customised policies are pulling text from the database instead of the template files, and are being treated differently.

If it's not possible to resolve the issue and make the %1$s and %2$s work, I would suggest creating a {{SITE_NAME}} and {{SITE_URL}} shortcode that can be used to manually ensure that those can be dynamically used.

**Comment by tas2580** [comment]
should be fixed with https://github.com/tas2580/privacyprotection/commit/a392f7c7f1f9a2139074d7a93d69fdefc04e291a
