### ISSUE TITLE
Fix the terms agreement step during registration.

### ISSUE THREAD

**Issue by 01i** [tas2580/privacyprotection#41]
When a new user registers for the site, they are first presented with the default phpbb terms agreement with buttons for `I agree` and `I disagree`. After agreeing to the terms, they are presented with the registration form.

There are two issues with this:

1. The policy form being presented to the user is taken from the language document. If the user has used this extension to customise the policy (or provided a URL for an alternative policy page), then the user is being forced to agree to an out of date policy in order to complete registration.

2. Following clicking `I Agree`, an additional `Privacy Policy Read and Accepted` radio button is being added by this extension to the registration form. The user is essentially accepting the policy twice during the registration process.

I would suggest one of two resolutions.

either
- Modify the pre-registration form policy page to correctly show the modified policy if it has been changed by this extension, or to provide some default text and a link to the URL based policy if configured that way.
- The  `I disagree` button should load the disagreement URL is one has been provided. 
- Then change the `privacy policy read and accepted` radio button on the registration form to a hidden field used to pass the date through to this extension. The user has already agreed in the previous step so doesn't need to agree again.

or 
- Bypass the pre-registration policy page so that new registrations go direct to the registration form. 

My personal preference would be for option 2. It's less work to implement, and would IMO provide a better UX.

**Comment by tas2580** [comment]
The thing that you have to agree in the first step are the "terms of use" and not the privacy policy. This are different things.

**terms of use** = Thinks like don't say asshole to other users or don't post porn pics
**privacy policy** = How the forum handles private data

To register you have to agree both.

**Comment by 01i** [comment]
To be honest, I hadn't noticed the difference. Having compared the two sets of text , I still feel that this extension should be taking care of that first page though.

For example, the default terms policy mentions that they can be changed at any time without further agreement, and I wouldn't think that's fully compatible with GPDR

Also, the default terms policy mentions IP collection (something that this extension can change), and suggests that the site holds no responsibility for your data if hacked, which isn't true under GDPR.

**Comment by tas2580** [comment]
>For example, the default terms policy mentions that they can be changed at any time without further agreement, and I wouldn't think that's fully compatible with GPDR

This has nothing to do with GPDR. I had a phpBB 3.0 Mod for this -> https://github.com/tas2580/phpBB-3.0-Accept-terms maybe there is a similar extension.

>Also, the default terms policy mentions IP collection (something that this extension can change), and suggests that the site holds no responsibility for your data if hacked, which isn't true under GDPR.

But this is a problem of the phpBB core, or the core language files.

If you want handle the terms policy, this would be an extra extension.
