### ISSUE TITLE
Fehlende Übersetzung

### ISSUE THREAD

**Issue by Joyce-Luna** [tas2580/privacyprotection#44]
Kirk hat folgendes gemeldet https://www.phpbb.de/community/viewtopic.php?p=1382960#p1382960

	'ACP_REJECT_URL_EXPLAIN'					=> 'If a URL is specified here, the update message will issue an additional button for disapproving the privacy policy, that points to the URL provided here',

Dort fehlt
	'ACP_FOOTERLINK'							=> 'Link in Footer',
	'ACP_FOOTERLINK_EXPLAIN'					=> 'Should a link to the privacy policy be displayed in the footer?',

Auch in DE würde es fehlen

**Comment by Kirk-phpbb** [comment]
Es fehlt nur in EN bei DE ist es vorhanden.

**Comment by Joyce-Luna** [comment]
Stimmt, du hast es in einer anderen Zeile platziert und ich habe nur darauf geachtet.

**Comment by tas2580** [comment]
https://github.com/tas2580/privacyprotection/issues/11
