### ISSUE TITLE
Download only posts accessible to the user

### ISSUE THREAD

**Issue by canonknipser** [tas2580/privacyprotection#45]
Currently, ucp function "download posts" grabs all posts from posts table written by the user, regardless of the status (approved, unapproved, softdeleted) or permission (maybe the post was moved to a protected forum).

The function should respect user's permission to read the posts

**Comment by Scanialady** [comment]
I am of the opposite opinion. The regulation does not say "data that the person can see for himself". The regulation says "all personal data stored about the person concerned".

**Comment by tas2580** [comment]
I think a option in ACP for this would be good.
