### ISSUE TITLE
Automatische weiterleitung nach akzeptieren der Datenschutzerklärung

### ISSUE THREAD

**Issue by Kirk-phpbb** [tas2580/privacyprotection#48]
Nach dem der User der Datenschutzerklärung zugestimmt hat, bekommt er die Mitteilung das er die Datenschutzerklärung erfolgreich akzeptiert hat.
Es wäre evtl. sinnvoll eine automatische weiterleitung zu machen.
In der listener.php das hier:
`				$this->user->add_lang_ext('tas2580/privacyprotection', 'common');
				trigger_error($this->user->lang['PRIVACY_ACCEPT_SUCCESS']);
				//redirect(append_sid("{$this->phpbb_root_path}index.{$this->php_ext}"));
			}
`
durch das ersetzen:
`				meta_refresh(5, $redirect_url);
				$this->user->add_lang_ext('tas2580/privacyprotection', 'common');
				trigger_error($this->user->lang['PRIVACY_ACCEPT_SUCCESS']);
				$redirect_url = (append_sid("{$this->phpbb_root_path}index.{$this->php_ext}"));

				redirect($redirect_url);
			}
`

**Comment by tas2580** [comment]
Ich hatte je die 301 Weiterleitung drin, aber das hat unter manchen PHP Versionen Probleme gemacht, deshalb jetzt die Meldung.
Das mit dem Meta Refresh wäre natürlich eine Idee.
