### ISSUE TITLE
Fehlende Einträge in den Language Dateien

### ISSUE THREAD

**Issue by Kirk-phpbb** [tas2580/privacyprotection#49]
Auf Grund diesem Beitrages: [https://www.phpbb.de/community/viewtopic.php?p=1383021#p1383021](url)
In den Language Dateien `de/acp.php` und `en/acp.php` fehlen folgende Einträge:
`	'USER_LIST_NOT_ACEPTED_EXPLAIN'			=> 'Liste der User die der Datenschutzerklärung nicht zugestimmt haben.',
	'USER_LIST_ACEPTED_EXPLAIN'				=> 'Liste der User die der Datenschutzerklärung zugestimmt haben.',
`	'USER_LIST_NOT_ACEPTED_EXPLAIN'				=> 'List of users who did not agree to the privacy policy.',
	'USER_LIST_ACEPTED_EXPLAIN'					=> 'List of users who have agreed to the privacy policy.',
`

**Comment by tas2580** [comment]
Hm, das sollte eigentlich gar nicht mehr drin sein.

**Comment by Kirk-phpbb** [comment]
Brauchen tut man es nicht, nur seltsam das ich diese Fehlermeldung nicht hatte.
Vermutlich weil ich noch kein php7 im Einsatz habe.
