### ISSUE TITLE
Stop users from using mChat if not accepted

### ISSUE THREAD

**Issue by Solidjeuh** [tas2580/privacyprotection#50]
I noticed this ext blocks users from posting in the forum if they not accept the policy. I think it's a great idea to add an event that also prevents them to leave a message in the mChat ext, because it also stores IP addresses.

[https://github.com/dmzx/mChat](url)

**Comment by tas2580** [comment]
Can't you use group permissions for that?

**Comment by Solidjeuh** [comment]
You mean make a new group with minimum permissions and select that group in the privacy ACP settings?  So user that wont accept are added to that group?

**Comment by Solidjeuh** [comment]
Oke found it. Sorry to bother you :) All works perfect! 👍
