### ISSUE TITLE
Internal server error while anonymizing all stored IPs / Missing labels in ACP settings

### ISSUE THREAD

**Issue by happykeppi** [tas2580/privacyprotection#53]
Database server: MySQL(i) 5.6.19-67.0-log 	
PHP version: 5.6.31 
Board version: 3.2.2 
Privacy protection: 0.2.2 
--------------------------
Using the 'Anonymize all stored IPs' function gives me the following error:

> "AJAX error
> Internal Server Error"

This was what the php error log says

> PHP Fatal error:  Call to a member function trigger_event() on null in [phpBB]/ext/tas2580/privacyprotection/acp/privacyprotection_module.php on line 92
> PHP Fatal error:  Call to a member function trigger_event() on null in [phpBB]board/ext/tas2580/privacyprotection/acp/privacyprotection_module.php on line 92

Furthermore I have some missing labels in the ACP settings section (see screenshot below):

![p1120719](https://user-images.githubusercontent.com/13066275/40079488-5d45efd4-5888-11e8-9579-6a08613e07ef.jpg)

**Comment by tas2580** [comment]
https://github.com/tas2580/privacyprotection/commit/3a3bcbff5bd2e0caf29fbfeb710bc876ca2bae5e#diff-55112b2e4373cabe034f407eba3dd54eL17
