### ISSUE TITLE
Five labels still missing in version 0.2.3

### ISSUE THREAD

**Issue by happykeppi** [tas2580/privacyprotection#54]
Thank you for the latest, updated version 0.2.3. However, the following language labels are still missing in the ACP settings section:

ACP_MOVE_GROUP
ACP_REG_ACCEPT_PRIVACY_EXPLAIN
ACP_REG_ACCEPT_MAIL_EXPLAIN
ACP_ANONYMIZE_IP_TIME_EXPLAIN
ACP_DELETE_IP_EXPLAIN

**Comment by tas2580** [comment]
https://github.com/tas2580/privacyprotection/pull/56
