### ISSUE TITLE
Questions to cookies and export

### ISSUE THREAD

**Issue by janzev** [tas2580/privacyprotection#55]
I have a few questions or feature requests.

Is it possible to change the link and text in the cookie notification, so that it points to the local privacy policy?
Does the data export function only export data of user posts? Is it possible to expand the export to all saved user related information? --seems to be implemented already
Is there an option in ucp to download all my user related data? --seems to be implemented already
Would it be possible to deactivate setting of any cookies from phpBB when privacy policy is not accepted? 
Is it possible to revoke the acceptance of the privacy policy? This possibility should be there to be compliant to EU DSGVO in my opinion.

**Comment by tas2580** [comment]
> Is it possible to change the link and text in the cookie notification, so that it points to the local privacy policy?

Overwrite `COOKIE_CONSENT_HREF` in /language/xx/common.php

> Would it be possible to deactivate setting of any cookies from phpBB when privacy policy is not accepted?

No

> Is it possible to revoke the acceptance of the privacy policy? This possibility should be there to be compliant to EU DSGVO in my opinion.

With next update
