### ISSUE TITLE
Use extension for other themes than "prosilver"

### ISSUE THREAD

**Issue by sebeichholz** [tas2580/privacyprotection#71]
Hi,
I am installing your extension to my phpbb 3.2 board.
I also want to use another them apart from the default "prosilver" theme (BBOOTS).
Is this possible? I don't see anything from you extension when I switch to the other theme (no footer links, and most important the "Privacy Policy updated" area is completely missing.

What has to be done that you extension works in another theme?
I might take some time to support you with this, but I don't know what to do :-)

Thanks!

**Comment by tas2580** [comment]
I think it's because the Template Events are missing in your theme. Can you provide a download link for the theme?

**Comment by sebeichholz** [comment]
No I can't, it's a commercial theme :-(
I already thought that it's the "events", I never worked with phpbb templates before but I found something in the documentation about it.

Which are the events I have to look for in the theme?
Is it the six files in the folder "styles/prosilver/template/event/" ?
And would I have to duplicate the styles/prosilver folder to make them work with the other theme?

**Comment by sebeichholz** [comment]
Ah now I found it: I had to purge the phpbb cache! 
So the events are there and everything is working.
No I need to style things a little bit.
