### ISSUE TITLE
Use /styles/all instead of /styles/prosilver ?

### ISSUE THREAD

**Issue by RonaldKools** [tas2580/privacyprotection#81]
When using another templateset than Prosilver, the privacy statement selection will not show up up in the registration form.

If the "all" templateset would be used instead, it works out of the box with all templatesets.

Right now I make a copy of the /styles/prosilver folder and rename this copy to all, but maybe you can use /styles/all by default?

**Comment by tas2580** [comment]
The Extension uses HTML codes witch is not compatible to all styles. If you use only prosilver based styles you can rename "prosilver" to "all". But this should be not default,
